name: Generate Snake Animation (Tokyonight Theme)

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC
  workflow_dispatch: # Allow manual trigger from Actions tab
  push: # Also run immediately on any push to main
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: Nemick
          outputs: dist/snake.svg
          color_snake: "#70A5FD"
          color_dots: "#38BDAE,#F7768E,#FF9E64,#E0AF68,#9ECE6A"

      - name: Push snake.svg to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
